// Original MIT fixture; generated by utility-native-go.mjs.
package failure
import "testing"
func TestNativeFailureContext(t *testing.T) {
	t.Log("HUGR_GO_FAILURE_CONTEXT: café 🧭")
	t.Fatal("HUGR_GO_FAILURE_SENTINEL: original nonzero evidence")
}
