// Original MIT fixture; generated by utility-native-go.mjs.
package diagnostic
import "testing"
func TestNativeDiagnosticOnly(t *testing.T) {
	t.Log("HUGR_GO_DIAGNOSTIC_SENTINEL: successful log remains evidence café 🧭")
}
