// Original MIT fixture; generated by utility-native-go.mjs.
package opaque
import ("fmt"; "os"; "testing")
func TestNativeOpaqueOutput(t *testing.T) {
	fmt.Println("HUGR_GO_OPAQUE_SENTINEL: unframed stdout café 🧭")
	fmt.Fprintln(os.Stderr, "HUGR_GO_STDERR_SENTINEL: native stderr café 🧭")
}
